# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: dllllb/rllr-artifacts
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains your PAT
        path: experiments/artifacts
        fetch-depth: 1
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev
    - name: Test with pytest
      run: |
        cd experiments/montezuma
        pipenv run pytest enjoy.py
        cd -
        cd experiments/minigrid
        pipenv run pytest enjoy.py
        cd -
        pipenv run pytest
