name: RLLR tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        repository: dllllb/rllr-artifacts
        token: ${{ secrets.GH_PAT }} # `GH_PAT` is a secret that contains personal GitHub token
        path: experiments/artifacts
        fetch-depth: 1
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv sync --dev
    - name: Test with pytest
      run: |
        pipenv run pytest experiments/montezuma/enjoy.py
        pipenv run pytest experiments/minigrid/enjoy.py
        pipenv run pytest
